[deps]
BasicPOMCP = "d721219e-3fc6-5570-a8ef-e5402f47c49e"
BayesNets = "ba4760a4-c768-5bed-964b-cf806dc591cb"
ContinuumWorld = "5cbb95a3-277b-5373-895a-7e14bd91b3cc"
D3Trees = "e3df1716-f71e-5df9-9e2d-98e193103c45"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiscreteValueIteration = "4b033969-44f6-5439-a48b-c11fa3648068"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GridInterpolations = "bb4c363b-b914-514b-8517-4eb369bc008a"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
LaserTag = "041f53e1-e4f8-54ec-814d-e9e995aa38d4"
MCTS = "e12ccd36-dcad-5f33-8774-9175229e7b33"
NBInclude = "0db19996-df87-5ea3-a455-e3a50d440464"
PGFPlots = "3b7a836e-365b-5785-a47d-02c71176b4aa"
POMDPModelTools = "08074719-1b2a-587c-a292-00f91cc44415"
POMDPModels = "355abbd5-f08e-5560-ac9e-8b5f2592a0ca"
POMDPPolicies = "182e52fb-cfd0-5e46-8c26-fd0667c990f4"
POMDPSimulators = "e0d0a172-29c6-5d4e-96d0-f262df5d01fd"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
Reactive = "a223df75-4e93-5b7c-acf9-bdd599c0f4de"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TikzPictures = "37f6aa50-8035-52d0-81c2-5a1d08754b2d"
